### ISSUE TITLE
Upgrade to 0.17.0

### ISSUE THREAD

**Issue by halfzebra** [elm-community/elm-string-split#4]
I would love to have this package available for 0.17.0

There is a PR pending #2

**Comment by jvoigtlaender** [comment]
@halfzebra, you said you would like to have this package available for 0.17. But what about https://github.com/elm-community/elm-string-split/issues/5? Any thoughts/comments on that?

**Comment by halfzebra** [comment]
@jvoigtlaender good idea, thanks for a hint, it looks like `chunksOfLeft` is already there. I will close this issue, since #5 makes perfect sense to me.
